export const CATEGORYTYPE = {
  CATEGORY_LIST_LOADING:"CATEGORY_LIST_LOADING",
  CATEGORY_LIST_SUCCESS:"CATEGORY_LIST_SUCCESS",
  CATEGORY_LIST_ERROR:"CATEGORY_LIST_ERROR",
  CATEGORY_LIST_RESET:"CATEGORY_LIST_RESET",

  CATEGORY_CREATE_LOADING:"CATEGORY_CREATE_LOADING",
  CATEGORY_CREATE_SUCCESS:"CATEGORY_CREATE_SUCCESS",
  CATEGORY_CREATE_ERROR:"CATEGORY_CREATE_ERROR",
  CATEGORY_CREATE_RESET:"CATEGORY_CREATE_RESET",

  CATEGORY_UPDATE_LOADING:"CATEGORY_UPDATE_LOADING",
  CATEGORY_UPDATE_SUCCESS:"CATEGORY_UPDATE_SUCCESS",
  CATEGORY_UPDATE_ERROR:"CATEGORY_UPDATE_ERROR",
  CATEGORY_UPDATE_RESET:"CATEGORY_UPDATE_RESET",

  CATEGORY_DELETE_LOADING:"CATEGORY_DELETE_LOADING",
  CATEGORY_DELETE_SUCCESS:"CATEGORY_DELETE_SUCCESS",
  CATEGORY_DELETE_ERROR:"CATEGORY_DELETE_ERROR",
  CATEGORY_DELETE_RESET:"CATEGORY_DELETE_RESET",
}