export const NEWSTYPE = {
  NEWS_LIST_LOADING:"NEWS_LIST_LOADING",
  NEWS_LIST_SUCCESS:"NEWS_LIST_SUCCESS",
  NEWS_LIST_ERROR:"NEWS_LIST_ERROR",
  NEWS_LIST_RESET:"NEWS_LIST_RESET",

  NEWS_DETAIL_LOADING:"NEWS_DETAIL_LOADING",
  NEWS_DETAIL_SUCCESS:"NEWS_DETAIL_SUCCESS",
  NEWS_DETAIL_ERROR:"NEWS_DETAIL_ERROR",
  NEWS_DETAIL_RESET:"NEWS_DETAIL_RESET",

  HOME_NEWS_LOADING:"HOME_NEWS_LOADING",
  HOME_NEWS_SUCCESS:"HOME_NEWS_SUCCESS",
  HOME_NEWS_ERROR:"HOME_NEWS_ERROR",
  HOME_NEWS_RESET:"HOME_NEWS_RESET",
}