export const NEWSTYPE = {
  NEWS_LIST_LOADING:"NEWS_LIST_LOADING",
  NEWS_LIST_SUCCESS:"NEWS_LIST_SUCCESS",
  NEWS_LIST_ERROR:"NEWS_LIST_ERROR",
  NEWS_LIST_RESET:"NEWS_LIST_RESET",

  NEWS_DETAIL_LOADING:"NEWS_DETAIL_LOADING",
  NEWS_DETAIL_SUCCESS:"NEWS_DETAIL_SUCCESS",
  NEWS_DETAIL_ERROR:"NEWS_DETAIL_ERROR",
  NEWS_DETAIL_RESET:"NEWS_DETAIL_RESET",

  NEWS_CREATE_LOADING:"NEWS_CREATE_LOADING",
  NEWS_CREATE_SUCCESS:"NEWS_CREATE_SUCCESS",
  NEWS_CREATE_ERROR:"NEWS_CREATE_ERROR",
  NEWS_CREATE_RESET:"NEWS_CREATE_RESET",

  NEWS_UPDATE_LOADING:"NEWS_UPDATE_LOADING",
  NEWS_UPDATE_SUCCESS:"NEWS_UPDATE_SUCCESS",
  NEWS_UPDATE_ERROR:"NEWS_UPDATE_ERROR",
  NEWS_UPDATE_RESET:"NEWS_UPDATE_RESET",

  NEWS_DELETE_LOADING:"NEWS_DELETE_LOADING",
  NEWS_DELETE_SUCCESS:"NEWS_DELETE_SUCCESS",
  NEWS_DELETE_ERROR:"NEWS_DELETE_ERROR",
  NEWS_DELETE_RESET:"NEWS_DELETE_RESET",
}