export const AUTHTYPE = {
  LOGIN_LOADING:"LOGIN_LOADING",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_ERROR:"LOGIN_ERROR",

  SIGNUP_LOADING:"SIGNUP_LOADING",
  SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
  SIGNUP_ERROR:"SIGNUP_ERROR",
}